Repository emergenzeHack/covid19italia, pull requests merged in 2020-04, with the labels that each got.

#385 Fix overlap issue list
  css/main.css
Labels: css, frontend, per sviluppatori

#386 Update index.html
  index.html
Labels: international

#388 Cambiato colore pulsanti
  issues.md
  regioni.md
Labels: css, frontend, per sviluppatori

#396 Update _config.yml
  _config.yml
Labels: international

#403 Update chiedi-aiuto.html
  _segnalazioni/chiedi-aiuto.html
Labels: international

#407 Update segnala.md
  segnala.md
Labels: international

#481 Lang gr
  about.md
  js/cookie.js
Labels: gr branch, international

#518 Fix problema navbar
  css/main.css
Labels: bug, development, frontend, gr branch

#545 Aggiornata wiki sviluppatori con documentazione docker
  wiki/Sviluppare-in-locale-sul-sito.md
Labels: documentation, enhancement
