Repository emergenzeHack/covid19italia, pull requests merged in 2020-03, with the labels that each got.

#211 ♻️✨ Incorpora i form
  _config.yml
  _segnalazioni/bufala.md
  _segnalazioni/chiedi-aiuto.md
  _segnalazioni/contatto-utile.md
  _segnalazioni/documenti-dati.md
  _segnalazioni/dona-beni-servizi.md
  _segnalazioni/iniziative-servizi.md
  _segnalazioni/notizia.md
  _segnalazioni/raccolta-fondi.md
  css/main.css
  css/responsive_iframes.css
  segnala.md
Labels: enhancement, per sviluppatori

#209 📌 Tracks Gemfile.lock with Bundler 1.x
  .gitignore
  .gitlab-ci.yml
  Gemfile.lock
Labels: per sviluppatori

#321 Troncare testo issue nella issue list
  _layouts/issuelist.html
Labels: frontend

#324 Markup JSON-LD
  dataset.md
  index.html
Labels: frontend, seo

#323 Titolo e descrizione issue
  _layouts/issue.html
Labels: frontend

#329 Cambio navbar e themecolor
  _includes/head.html
  css/main.css
  manifest.json
Labels: frontend

#330 Aggiunto cambio lingua nel menù
  _includes/nav.html
  _layouts/base.html
Labels: frontend, international

#338 mappa
  _layouts/issuelist.html
Labels: frontend

#339 form ricerca
  index.html
Labels: frontend

#340 form ricerca
  searchissues.html
Labels: frontend

#356 Fix responsiveness testo card home page
  index.html
Labels: bug, frontend

#361 Fix home piccola e word break
  _layouts/homepage.html
  index.html
Labels: Urgente, frontend, per sviluppatori
